print(" Hello World")
s="ABCD abcd Efaqghi eFIGH"
print("  Main string ")
print(s)
print()
print(len(s))
print(s.capitalize())
print(s.center(60,"*"))
print(s.count("a"))
print(s.endswith("H"))
print(s.find("aq"))
print(s.index("a",6))
print(s.isalnum(),"because space is in the string")
print("1234assdf".isalnum())
print("assdf".isalnum())
print("1234".isalnum())
print(s.isalpha(),"because here only consider alphabet")
print("asfhgdshg".isalpha())
print("165454".isdecimal(),"if value in .(point) ther false")
print("234".isdigit(),"     Only comnsider number")
print("abcd12".isidentifier())
print(s.islower())
print("ajasvdhj".islower())
print("%&8!@#+)(".isprintable())
print(s.isspace())
print(" ".isspace())
print(s.istitle())
print("Abcd Efgh".istitle())
print("ABCD".isupper())
print(s.startswith("A"))
print(s.lower())
print(s.upper())
print(s.title())
print(s.swapcase())
print(s.replace("a","*"))
print(s.split())

